name: Update Image Reference
on:
  repository_dispatch:
    types: gitops-example-app-trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v2
      - name: Update Version In Checked-Out Code
        if: ${{ github.event.client_payload.sha }}
        run: |
          sed -i "s@\(.*image:\).*@\1 docker.io/${{secrets.DOCKER_USER}}/podinfo:${{ github.event.client_payload.sha }}@" ${GITHUB_WORKSPACE}/kustomize/deployment.yaml
      - name: Commit The New Image Reference
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event.client_payload.sha }}
        with:
          commit_message: Deploy new image ${{ github.event.client_payload.sha }}
          branch: main
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: Example GitOps Bot
          commit_user_email: gitops-example-bot@container-solutions.com
          commit_author: Example GitOps Bot <gitops-example-bot@container-solutions.com>
